version: '3'

services:
  # DB
  db:
    container_name: app-db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    networks:
      - todo-spring
  # phpmyadmin
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - todo-spring
  # spring-to-do
#  spring-to-do:
#    container_name: spring-to-do
#    depends_on:
#      - phpmyadmin
#    image: riawolf/spring-to-do
#    restart: always
#    ports:
#      - '80:8080'
#    networks:

networks:
  todo-spring:
volumes:
  db_data: